services: 

  db:
      image: postgres:16-alpine
      container_name: 69-s2-db
      ports:
        - 54321:5432
      environment:
        - POSTGRES_PASSWORD=B065051
        - POSTGRES_USER=BRIGHT
        - POSTGRES_DB=MY_DB
      volumes:
      - ./data-postgres:/var/lib/postgresql/data
        
  admin:
    image: dpage/pgadmin4
    container_name: 69-s2-admin
    ports:
      - 8082:80
    environment:
      - PGADMIN_DEFAULT_PASSWORD=12345
      - PGADMIN_DEFAULT_EMAIL=napat-sr@rmutp.ac.th

volumes:
  data-postgres:
    

  
